### ISSUE TITLE
Support new anonfile filesize limit

### ISSUE THREAD

**Issue by jadedgnome** [tallpants/share-anything#5]
Anonfile increased their filesize limit and the script doesn't support files greater than 5GB.

"We offer you 10 GB filesize limit and unlimited bandwidth."

"

**Comment by tallpants** [comment]
Do you want to open a PR for this @jadedgnome ?

You just have to change this line: https://github.com/tallpants/share-anything/blob/master/share/hosts/anonfile.py#L29

**Comment by jadedgnome** [comment]
@tallpants I edited that line and now i'm getting an error after running "python setup.py install".

ImportError: cannot import name helpers

**Comment by tallpants** [comment]
I made the change myself and pushed to master. Can you delete your copy, clone it again, and then try `python setup.py install`?

**Comment by tallpants** [comment]
I'm archiving this repository @jadedgnome, I don't use this script myself and I really don't have any interest in maintaining it. It's super simple code so you should be able to maintain a fork of it yourself if you want to. Sorry!
